//! # Prometheus metrics registry — polish pass (Apr 2026)
//!
//! A self-contained, **dep-free** metrics module for `chimere-server`.
//! All counters are `AtomicU64` so the hot path (per-request / per-token
//! increments) does not take any lock. The module provides:
//!
//! - [`Metrics`] — shared registry held on [`AppState::metrics`] as
//!   `Arc<Metrics>`. Its hook methods (`inc_request_ok`, `add_prompt_tokens`,
//!   `add_gen_tokens`, `observe_ttft_ms`) are `O(1)` and non-blocking.
//! - [`Metrics::render_prometheus`] — builds a Prometheus `text/plain;
//!   version=0.0.4; charset=utf-8` body from the atomic snapshots. Called
//!   once per scrape; format is the standard exposition format documented
//!   at <https://prometheus.io/docs/instrumenting/exposition_formats/>.
//! - [`Metrics::snapshot_json`] — `serde_json::Value` with the same fields
//!   for the enriched `/v1/status` handler.
//!
//! ## Why no crates
//!
//! Adding `prometheus`, `metrics`, or `hdrhistogram` would pull 10+
//! transitive deps (all of `tokio-util`, `hyper`, an extra locked HashMap,
//! ...). The feature surface we need here — 4 counters, 2 gauges, one
//! 100-sample ring for TTFT quantiles — is ~200 lines of stdlib code with
//! zero dep cost. The `/metrics` route is scraped at most once every
//! 15 seconds by Prometheus, so the single `Mutex` around the TTFT ring
//! buffer is not a contention risk.
//!
//! ## TTFT quantile sketch
//!
//! We keep the last `TTFT_RING_CAP = 100` TTFT samples in a small ring
//! buffer guarded by a `std::sync::Mutex`. On scrape we `clone()` the ring,
//! sort it, and pick quantiles at `[0.5, 0.9, 0.95, 0.99]`. This is good
//! enough for a polish pass — the J7 stress harness and real observability
//! (once we need proper histograms) can swap in `prometheus::Histogram`
//! later. The Prometheus `summary` type is used (not `histogram`) because
//! with 100 samples we can report exact quantiles, not bucketed ones.
//!
//! ## Counter hook sites (callers in `server.rs`)
//!
//! | Event                          | Call                                     |
//! |--------------------------------|------------------------------------------|
//! | Non-streaming request OK       | `state.metrics.inc_request_ok()`         |
//! | Non-streaming request err      | `state.metrics.inc_request_error()`      |
//! | Streaming request admitted     | `state.metrics.inc_request_ok()` (at Done)|
//! | Prompt tokens counted          | `state.metrics.add_prompt_tokens(n)`     |
//! | Generated tokens counted       | `state.metrics.add_gen_tokens(n)`        |
//! | First token arrived (stream)   | `state.metrics.observe_ttft_ms(ms)`      |
//!
//! See `APPLY.md` for the exact insert sites (marker-comment guided diff).

use std::sync::Mutex;
use std::sync::atomic::{AtomicU64, Ordering};

/// Size of the TTFT ring buffer. 100 samples is enough for stable p50/p95
/// in a polish pass without a proper histogram crate. Overwrites oldest on
/// push. See module docs for rationale.
pub const TTFT_RING_CAP: usize = 100;

/// Prometheus `text/plain` content type with the protocol version suffix.
/// Use this as the `Content-Type` header on `/metrics` responses.
pub const PROM_CONTENT_TYPE: &str = "text/plain; version=0.0.4; charset=utf-8";

/// Shared metrics registry. Hold as `Arc<Metrics>` on `AppState`.
///
/// All fields are `pub(crate)` so tests in the same crate can inspect them
/// directly; external callers use the `inc_*` / `add_*` / `observe_*` hooks.
///
/// The `slot_occupancy` and `slot_pool_size` gauges are *not* kept as
/// atomics — they're derived on-the-fly from the `NativeScheduler` / legacy
/// `Scheduler` at render time so we never drift out of sync with the
/// scheduler's view of the world. See [`Metrics::render_prometheus`].
#[derive(Debug)]
pub struct Metrics {
    /// `chimere_requests_total{status="ok"}` — successful chat completions
    /// (both streaming Done and non-streaming 200 OK).
    pub(crate) requests_ok: AtomicU64,
    /// `chimere_requests_total{status="error"}` — any path returning a
    /// non-2xx or emitting a terminal `Error` frame in SSE.
    pub(crate) requests_error: AtomicU64,
    /// `chimere_prompt_tokens_total` — sum of prompt tokens across all
    /// accepted requests. Counted after tokenisation, before admission.
    pub(crate) prompt_tokens_total: AtomicU64,
    /// `chimere_gen_tokens_total` — sum of tokens generated by the model,
    /// including tokens emitted inside `<think>` blocks (which the client
    /// consumes via the SSE `reasoning_content` delta). Incremented on Done
    /// for non-streaming (with `completion_tokens`), per-token for streaming
    /// on both `Token` and `Thinking` events. See the streaming handlers in
    /// `server.rs` for the exact hook sites.
    pub(crate) gen_tokens_total: AtomicU64,
    /// Ring buffer of the last N TTFT samples (milliseconds). See
    /// [`TTFT_RING_CAP`]. Guarded by a Mutex — scrapes are rare, pushes
    /// are one-per-request so contention is negligible.
    pub(crate) ttft_ring: Mutex<TtftRing>,
}

/// Small fixed-capacity ring buffer of `u32` millisecond samples. We use
/// `u32` so 100 samples = 400 bytes — fits in a single cache line pair.
/// Overflow wraps around via `head`.
#[derive(Debug)]
pub(crate) struct TtftRing {
    buf: Vec<u32>,
    head: usize,
    filled: bool,
}

impl TtftRing {
    fn new(cap: usize) -> Self {
        Self {
            buf: vec![0u32; cap],
            head: 0,
            filled: false,
        }
    }

    /// Push a sample. O(1). If `ms > u32::MAX` (unreasonable TTFT — means
    /// the driver stalled), we clamp to `u32::MAX` rather than silently
    /// overflow.
    fn push(&mut self, ms: u64) {
        let clamped = if ms > u32::MAX as u64 { u32::MAX } else { ms as u32 };
        self.buf[self.head] = clamped;
        self.head = (self.head + 1) % self.buf.len();
        if self.head == 0 {
            self.filled = true;
        }
    }

    /// Snapshot valid samples (without the unfilled tail). Empty on
    /// first scrape before any request completed. Cheap clone — Vec of
    /// u32, at most `TTFT_RING_CAP` entries.
    fn snapshot(&self) -> Vec<u32> {
        let n = if self.filled { self.buf.len() } else { self.head };
        self.buf[..n].to_vec()
    }
}

impl Default for Metrics {
    fn default() -> Self {
        Self::new()
    }
}

impl Metrics {
    /// Build a fresh registry. All counters start at 0.
    pub fn new() -> Self {
        Self {
            requests_ok: AtomicU64::new(0),
            requests_error: AtomicU64::new(0),
            prompt_tokens_total: AtomicU64::new(0),
            gen_tokens_total: AtomicU64::new(0),
            ttft_ring: Mutex::new(TtftRing::new(TTFT_RING_CAP)),
        }
    }

    // ------------------------------------------------------------------
    // Hot-path hooks (called from HTTP handlers and worker threads)
    // ------------------------------------------------------------------

    /// Record a successful request. Cheap — one atomic increment.
    #[inline]
    pub fn inc_request_ok(&self) {
        self.requests_ok.fetch_add(1, Ordering::Relaxed);
    }

    /// Record a failed request (4xx / 5xx / SSE terminal Error).
    #[inline]
    pub fn inc_request_error(&self) {
        self.requests_error.fetch_add(1, Ordering::Relaxed);
    }

    /// Add prompt tokens accounted by the tokenizer *before* admission.
    /// Called exactly once per request on entry to the handler.
    #[inline]
    pub fn add_prompt_tokens(&self, n: usize) {
        self.prompt_tokens_total
            .fetch_add(n as u64, Ordering::Relaxed);
    }

    /// Add generated tokens. Call on Done for non-streaming (with
    /// `completion_tokens`), or incrementally per-token for streaming
    /// (with `1`). Thinking / `reasoning_content` tokens count as well —
    /// they are model-generated tokens consumed by the client.
    #[inline]
    pub fn add_gen_tokens(&self, n: usize) {
        self.gen_tokens_total
            .fetch_add(n as u64, Ordering::Relaxed);
    }

    /// Record a TTFT sample (milliseconds). Taken ONCE per streaming
    /// request, at the moment the first content token is pushed through
    /// the SSE channel. For non-streaming, TTFT == total latency — the
    /// handler still calls this for comparability.
    pub fn observe_ttft_ms(&self, ms: u64) {
        if let Ok(mut ring) = self.ttft_ring.lock() {
            ring.push(ms);
        }
        // Poisoned mutex: skip silently. The only way a Mutex poisons is
        // a panic inside `push`, which cannot happen (no panics in ring).
    }

    // ------------------------------------------------------------------
    // Render targets
    // ------------------------------------------------------------------

    /// Build the Prometheus exposition body. Caller provides the live
    /// scheduler snapshot so occupancy/queue-depth gauges reflect the
    /// current tick, not a cached value.
    ///
    /// # Parameters
    ///
    /// - `slot_occupancy` — number of slots currently serving a request.
    ///   `0` when idle or when scheduler is disabled (legacy single-slot).
    /// - `slot_pool_size` — total slots (1 when legacy single-slot).
    /// - `admission_queue_depth` — number of requests parked in the
    ///   admission mpsc channel. Best-effort (mpsc doesn't expose depth
    ///   cheaply — see `NativeScheduler::queue_depth()` for the
    ///   approximation we use).
    ///
    /// # Output
    ///
    /// Plain-text body in Prometheus 0.0.4 format. Ends with a single
    /// `\n`. Does **not** include the `Content-Type` header — the caller
    /// sets that to [`PROM_CONTENT_TYPE`] when responding.
    pub fn render_prometheus(
        &self,
        slot_occupancy: usize,
        slot_pool_size: usize,
        admission_queue_depth: usize,
    ) -> String {
        let ok = self.requests_ok.load(Ordering::Relaxed);
        let err = self.requests_error.load(Ordering::Relaxed);
        let pt = self.prompt_tokens_total.load(Ordering::Relaxed);
        let gt = self.gen_tokens_total.load(Ordering::Relaxed);

        // TTFT quantiles from the ring snapshot. If the ring is empty,
        // we skip the summary block entirely — Prometheus handles
        // missing series fine (they just don't appear in queries).
        let ttft_samples = self
            .ttft_ring
            .lock()
            .map(|r| r.snapshot())
            .unwrap_or_default();
        let (ttft_block, ttft_count, ttft_sum_ms) = render_ttft_summary(&ttft_samples);

        let mut out = String::with_capacity(2048);

        out.push_str(
            "# HELP chimere_requests_total Total chat-completion requests by terminal status\n\
             # TYPE chimere_requests_total counter\n",
        );
        out.push_str(&format!("chimere_requests_total{{status=\"ok\"}} {}\n", ok));
        out.push_str(&format!(
            "chimere_requests_total{{status=\"error\"}} {}\n",
            err
        ));

        out.push_str(
            "\n# HELP chimere_prompt_tokens_total Prompt tokens tokenised across all accepted requests\n\
             # TYPE chimere_prompt_tokens_total counter\n",
        );
        out.push_str(&format!("chimere_prompt_tokens_total {}\n", pt));

        out.push_str(
            "\n# HELP chimere_gen_tokens_total Tokens produced by the model across all requests\n\
             # TYPE chimere_gen_tokens_total counter\n",
        );
        out.push_str(&format!("chimere_gen_tokens_total {}\n", gt));

        out.push_str(
            "\n# HELP chimere_slot_occupancy Slots currently serving a request\n\
             # TYPE chimere_slot_occupancy gauge\n",
        );
        out.push_str(&format!("chimere_slot_occupancy {}\n", slot_occupancy));

        out.push_str(
            "\n# HELP chimere_slot_pool_size Total slots configured on this server instance\n\
             # TYPE chimere_slot_pool_size gauge\n",
        );
        out.push_str(&format!("chimere_slot_pool_size {}\n", slot_pool_size));

        out.push_str(
            "\n# HELP chimere_admission_queue_depth Requests parked in the admission mpsc channel\n\
             # TYPE chimere_admission_queue_depth gauge\n",
        );
        out.push_str(&format!(
            "chimere_admission_queue_depth {}\n",
            admission_queue_depth
        ));

        // TTFT summary is optional — only rendered when we have samples.
        // Prometheus is happy with an empty metric family (no series).
        if !ttft_samples.is_empty() {
            out.push_str("\n# HELP chimere_ttft_seconds Time to first token per streaming request (ring buffer quantiles, cap=");
            out.push_str(&TTFT_RING_CAP.to_string());
            out.push_str(")\n# TYPE chimere_ttft_seconds summary\n");
            out.push_str(&ttft_block);
            out.push_str(&format!("chimere_ttft_seconds_sum {:.6}\n", ttft_sum_ms / 1000.0));
            out.push_str(&format!("chimere_ttft_seconds_count {}\n", ttft_count));
        }

        out
    }

    /// Structured JSON snapshot for `/v1/status`. Mirrors the Prometheus
    /// fields; the caller assembles the outer status envelope (engine
    /// name, model, scheduler mode, etc.).
    pub fn snapshot_json(
        &self,
        slot_occupancy: usize,
        slot_pool_size: usize,
        admission_queue_depth: usize,
    ) -> serde_json::Value {
        let ok = self.requests_ok.load(Ordering::Relaxed);
        let err = self.requests_error.load(Ordering::Relaxed);
        let pt = self.prompt_tokens_total.load(Ordering::Relaxed);
        let gt = self.gen_tokens_total.load(Ordering::Relaxed);

        let ttft_samples = self
            .ttft_ring
            .lock()
            .map(|r| r.snapshot())
            .unwrap_or_default();
        let qs = compute_quantiles(&ttft_samples, &[0.5, 0.9, 0.95, 0.99]);

        let ttft_json = if ttft_samples.is_empty() {
            serde_json::Value::Null
        } else {
            serde_json::json!({
                "count": ttft_samples.len(),
                "p50_ms": qs[0],
                "p90_ms": qs[1],
                "p95_ms": qs[2],
                "p99_ms": qs[3],
            })
        };

        serde_json::json!({
            "requests_ok": ok,
            "requests_error": err,
            "prompt_tokens_total": pt,
            "gen_tokens_total": gt,
            "slot_occupancy": slot_occupancy,
            "slot_pool_size": slot_pool_size,
            "admission_queue_depth": admission_queue_depth,
            "ttft": ttft_json,
        })
    }
}

// ---------------------------------------------------------------------------
// Quantile helpers
// ---------------------------------------------------------------------------

/// Render the per-quantile summary lines for `chimere_ttft_seconds`.
/// Returns `(block, count, sum_ms)`. Quantiles use the R-7 linear
/// interpolation rule (Numpy default) — plenty for 100 samples.
fn render_ttft_summary(samples: &[u32]) -> (String, u64, f64) {
    if samples.is_empty() {
        return (String::new(), 0, 0.0);
    }
    let qs = compute_quantiles(samples, &[0.5, 0.9, 0.95, 0.99]);
    let mut out = String::with_capacity(256);
    for (q, ms) in [0.5, 0.9, 0.95, 0.99].iter().zip(qs.iter()) {
        // Prometheus summary wants seconds for *_seconds histograms/summaries.
        let seconds = *ms as f64 / 1000.0;
        out.push_str(&format!(
            "chimere_ttft_seconds{{quantile=\"{:.2}\"}} {:.6}\n",
            q, seconds
        ));
    }
    let sum_ms: f64 = samples.iter().map(|&v| v as f64).sum();
    (out, samples.len() as u64, sum_ms)
}

/// Compute the given quantiles from `samples`. Sorts a copy; does not
/// mutate the input. Returns milliseconds (matching sample type).
/// `quantiles` should be strictly in `[0.0, 1.0]`.
fn compute_quantiles(samples: &[u32], quantiles: &[f64]) -> Vec<u32> {
    if samples.is_empty() {
        return quantiles.iter().map(|_| 0u32).collect();
    }
    let mut sorted: Vec<u32> = samples.to_vec();
    sorted.sort_unstable();
    let n = sorted.len();
    quantiles
        .iter()
        .map(|&q| {
            // R-7 linear interpolation — same as numpy.quantile default.
            let pos = q * (n as f64 - 1.0);
            let lo = pos.floor() as usize;
            let hi = pos.ceil() as usize;
            if lo == hi {
                sorted[lo]
            } else {
                let frac = pos - lo as f64;
                let lo_v = sorted[lo] as f64;
                let hi_v = sorted[hi] as f64;
                (lo_v + frac * (hi_v - lo_v)).round() as u32
            }
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn counters_increment_and_add() {
        let m = Metrics::new();
        m.inc_request_ok();
        m.inc_request_ok();
        m.inc_request_error();
        m.add_prompt_tokens(100);
        m.add_prompt_tokens(50);
        m.add_gen_tokens(25);

        assert_eq!(m.requests_ok.load(Ordering::Relaxed), 2);
        assert_eq!(m.requests_error.load(Ordering::Relaxed), 1);
        assert_eq!(m.prompt_tokens_total.load(Ordering::Relaxed), 150);
        assert_eq!(m.gen_tokens_total.load(Ordering::Relaxed), 25);
    }

    #[test]
    fn ttft_ring_wraps_at_capacity() {
        let mut ring = TtftRing::new(4);
        for i in 0..6u64 {
            ring.push(i * 10); // 0, 10, 20, 30, 40, 50
        }
        // After 6 pushes on a cap-4 ring: buf = [40, 50, 20, 30], filled=true.
        let snap = ring.snapshot();
        assert_eq!(snap.len(), 4);
        let mut sorted = snap.clone();
        sorted.sort_unstable();
        assert_eq!(sorted, vec![20, 30, 40, 50]);
    }

    #[test]
    fn ttft_snapshot_before_filled_returns_prefix_only() {
        let mut ring = TtftRing::new(10);
        ring.push(5);
        ring.push(7);
        ring.push(9);
        let snap = ring.snapshot();
        assert_eq!(snap, vec![5, 7, 9]);
    }

    #[test]
    fn quantiles_empty_are_all_zero() {
        let qs = compute_quantiles(&[], &[0.5, 0.95]);
        assert_eq!(qs, vec![0, 0]);
    }

    #[test]
    fn quantiles_sorted_input_p50_p95() {
        // 100 samples, uniform 1..=100. p50 = 50 or 51 depending on
        // interpolation; R-7 on positions 0..99 gives pos = 0.5*99 = 49.5,
        // so (samples[49]+samples[50])/2 = (50+51)/2 = 50.5 → 51 after round.
        let v: Vec<u32> = (1..=100u32).collect();
        let qs = compute_quantiles(&v, &[0.5, 0.95]);
        assert_eq!(qs[0], 51); // p50 rounded
        // p95 at pos = 0.95*99 = 94.05 → samples[94] + 0.05*(samples[95]-samples[94])
        //                          = 95 + 0.05*1 = 95.05 → 95.
        assert_eq!(qs[1], 95);
    }

    #[test]
    fn render_prometheus_has_expected_families() {
        let m = Metrics::new();
        m.inc_request_ok();
        m.add_prompt_tokens(42);
        m.add_gen_tokens(13);
        m.observe_ttft_ms(120);
        m.observe_ttft_ms(250);

        let body = m.render_prometheus(1, 4, 0);
        assert!(body.contains("chimere_requests_total{status=\"ok\"} 1"));
        assert!(body.contains("chimere_requests_total{status=\"error\"} 0"));
        assert!(body.contains("chimere_prompt_tokens_total 42"));
        assert!(body.contains("chimere_gen_tokens_total 13"));
        assert!(body.contains("chimere_slot_occupancy 1"));
        assert!(body.contains("chimere_slot_pool_size 4"));
        assert!(body.contains("chimere_admission_queue_depth 0"));
        assert!(body.contains("chimere_ttft_seconds{quantile=\"0.50\"}"));
        assert!(body.contains("chimere_ttft_seconds_count 2"));
    }

    #[test]
    fn render_prometheus_omits_ttft_when_ring_empty() {
        let m = Metrics::new();
        let body = m.render_prometheus(0, 1, 0);
        assert!(!body.contains("chimere_ttft_seconds"));
    }

    #[test]
    fn snapshot_json_shape_is_stable() {
        let m = Metrics::new();
        m.inc_request_ok();
        m.observe_ttft_ms(100);
        let v = m.snapshot_json(2, 4, 3);
        assert_eq!(v["requests_ok"], 1);
        assert_eq!(v["slot_occupancy"], 2);
        assert_eq!(v["slot_pool_size"], 4);
        assert_eq!(v["admission_queue_depth"], 3);
        assert_eq!(v["ttft"]["count"], 1);
    }

    #[test]
    fn snapshot_json_ttft_null_when_empty() {
        let m = Metrics::new();
        let v = m.snapshot_json(0, 1, 0);
        assert!(v["ttft"].is_null());
    }
}
